apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adp

resources:
  - ../../base
  - secrets/sealed-postgres-secret.yaml
  - secrets/sealed-adp-server-secret.yaml

images:
  - name: ghcr.io/fff-rick/adp-server
    newName: ghcr.io/fff-rick/adp-server
    digest: sha256:b7a732cfc324a6fc827414f8ac05e31501c04aedc52a6168d05f495ab8efd79e

patches:
  - path: server-config.patch.yaml
