apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adp

resources:
  - ../../base
  - secrets/sealed-postgres-secret.yaml
  - secrets/sealed-adp-server-secret.yaml

images:
  - name: ghcr.io/fff-rick/adp-server
    newName: ghcr.io/fff-rick/adp-server
    digest: sha256:ac921cc4d9f61ce73e1bcb782a0100b1243f59bd2c1d0dbee1639e1725929562

patches:
  - path: server-config.patch.yaml
