apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adp

resources:
  - ../../base
  - secrets/sealed-postgres-secret.yaml
  - secrets/sealed-adp-server-secret.yaml

images:
  - name: ghcr.io/fff-rick/adp-server
    newName: ghcr.io/fff-rick/adp-server
    digest: sha256:864bc88ab3af5de46a5d779ed41faf2bc689e37e5b44c6bfac9640ed6101bd0e

patches:
  - path: server-config.patch.yaml
